AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%i':    '()'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Proc:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false